
#spring.application.name=apiGateway
#
#server.port=8091
#
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#
#
##eureka.client.instance.hostname=192.168.1.72
##eureka.client.instance.prefer-ip-address=true
#
#eureka.client.service-url.default-zone=http://localhost:8090/eureka





spring:
  cloud:
    gateway:
      routes:
        - id: Order-Service
          uri: http://www.localhost:8904
          predicates:
            - Path=/order-service/**
        - id: Product-Service
          uri: http://www.localhost:8903
          predicates:
            - Path=/product-service/**
        - id: User-Service
          uri: http://www.localhost:8902/
          predicates:
            - Path=/user-service/**

  application:
    name: apiGateway



server:
  port: 8901

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8900/eureka
