server:
  port: 8092

spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect
  application:
    name: UserService
  datasource:
    url: jdbc:mysql://localhost:3306/Microservice
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root






eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761
