server:
  port: 8904

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQLDialect
  application:
    name: Order-Service
  datasource:
    url: jdbc:mysql://localhost:3306/Microservice
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://www.localhost:8900/eureka
